config/routes.rb
Rails.application.routes.draw do
  resources :surveys
  get 'static_pages/home'
  
  get 'static_pages/toy'
  
  get 'static_pages/small'
  
  get 'static_pages/medium'
  
  get 'static_pages/large'
   
  get 'static_pages/xlarge'
  
  get 'static_pages/review'
  
  get 'static_pages/health'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end
  resources :questions do
    resources :answers
  end
  root 'static_pages#home'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :user
    has_many :answers
end

app/models/survey.rb
class Survey < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  has_many :questions
  has_many :answers
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    before_action :find_question
    before_action :find_answer, only: [:edit, :update, :destroy]
    before_action :authenticate_user!
    
    def create
        @answer = @question.answers.create(answer_params)
        @answer.user_id = current_user.id
        
        if @answer.save
            redirect_to question_path(@question)
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @answer.update(answer_params)
            redirect_to question_path(@question)
        else
            render 'edit'
        end
    end
    
    def destroy
        @answer.destroy
        redirect_to question_path(@question)
    end

    private
    
    def answer_params
        params.require(:answer).permit(:content)
    end
    
    def find_question
        @question = Question.find(params[:question_id])
    end
    
    def find_answer
        @answer = @question.answers.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_post
    before_action :find_comment, only: [:edit, :update, :destroy] 
    before_action :authenticate_user!
    
    def create
        @comment = @post.comments.create(comment_params)
        @comment.user_id = current_user.id
        if @comment.save
            redirect_to post_path(@post)
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @comment.update(comment_params)
            redirect_to post_path(@post)
        else render 'edit'
        end
    end
    
    def destroy
        @comment.destroy
        redirect_to post_path(@post)
    end
    
    private
    
    def comment_params
        params.require(:comment).permit(:content)
    end
    
    def find_post
        @post = Post.find(params[:post_id])
    end
    
    def find_comment
         @comment = @post.comments.find(params[:id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    
    def index
        @posts = Post.all.order("created_at DESC")
    end
    
    def show
    end
    
    def new
        @post = current_user.posts.build
    end
    
    def create
        @post = current_user.posts.build(post_params)
        if @post.save
            redirect_to posts_path
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @post.update(post_params)
            redirect_to post_path
        else
            render 'edit'
        end
    end
    
    def destroy
        @post.destroy
        redirect_to posts_path
    end
    
    private
    
    def post_params
        params.require(:post).permit(:title, :description)
    end
    
    def find_post
         @post = Post.find(params[:id])
    end
    
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_action :find_question, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    
    def index
        @questions = Question.all.order("created_at DESC")
    end
    
    def show
    end
    
    def new
        @question = current_user.questions.build
    end
    
    def create
        @question = current_user.questions.build(question_params)
        if @question.save
            redirect_to questions_path
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @question.update(question_params)
            redirect_to question_path
        else
            render 'edit'
        end
    end
    
    def destroy
        @question.destroy
        redirect_to questions_path
    end
    
    private
    
    def question_params
        params.require(:question).permit(:title, :details)
    end
    
    def find_question
        @question = Question.find(params[:id])
    end
    
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def review
  end
  
  def health
  end
  
  def toy
  end
  
  def small
  end
  
  def medium
  end
  
  def large
  end
  
  def xlarge
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def survey_params
      params.require(:survey).permit(:size, :appartment, :shed, :energy, :garden, :children, :wh)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/answers/_answer.html.erb
<p><%= answer.content %></p>
<p>Posted By <%= answer.user.email %> <%= time_ago_in_words(answer.created_at) %> ago</p>

<% if user_signed_in? %>
    <% if answer.user_id == current_user.id %>
        <%= link_to "Edit", edit_question_answer_path(answer.question, answer) %>
        <%= link_to "Delete", question_answer_path(answer.question, answer), method: :delete, data: { confirm: "Are you sure you want to delete this Answer?"} %>
    <% end %>
<% end %>

app/views/answers/_form.html.erb
<%= simple_form_for([@question, @question.answers.build]) do |f| %>
<%= f.input :content, label: "Answer" %>
<%= f.button :submit %>
<% end %>

app/views/answers/edit.html.erb
<h1>Edit Answer</h1>
<%= simple_form_for([@question, @answer]) do |f| %>
<%= f.input :content, label: "Answer" %>
<%= f.button :submit %>
<% end %>

app/views/comments/_comment.html.erb
<p><%= comment.content %></p>
<p>Posted By <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</p>

<% if user_signed_in? %>
<% if comment.user_id == current_user.id %>
    <%= link_to "Edit", edit_post_comment_path(comment.post, comment) %>
    <%= link_to "Delete", post_comment_path(comment.post, comment), method: :delete, data: { confirm: "Are you sure?"} %>
    <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
<%= f.input :content, label: "Comment" %>
<%= f.button :submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= simple_form_for([@post, @comment]) do |f| %>
<%= f.input :content, label: "Comment" %>
<%= f.button :submit %>
<% end %>

app/views/posts/_form.html.erb
<%=simple_form_for @post do |f| %>
<%= f.input :title, label: "Post Title" %>
<%= f.input :description %>
<%= f.button :submit %>
<%end%>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>

<div class = "col-md-4">
    <div class="post">
        <h2 class="post-title"><%= post.title %></h2>
        <%= link_to "View Post", post_path(post), class: "btn btn-default" %>     
    </div>
</div>
<% end %>


<% if user_signed_in? %>
          <p><%= link_to "New Post", new_post_path, class: "navbar navbar-text navbar-link" %></p>
        <% end%>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class= "container">
    <h2><%= @post.title %></h2>
    <p>Posted By <%= @post.user.email %> <%= time_ago_in_words(@post.created_at) %> ago</p>
    <p><%= @post.description %></p>
    
    
    <h3>Comments:</h3>
    <%= render @post.comments %>
    
    <h3>Reply to Post:</h3>
    <%= render 'comments/form' %>
    
    <%= link_to "Back", posts_path %>
    <% if user_signed_in? %>
        <% if @post.user_id == current_user.id %>
            <%= link_to "Edit", edit_post_path(@post) %>
            <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to Delete this Post?" } %>
        <% end %>
    <% end %>
</div>

app/views/questions/_form.html.erb
<%=simple_form_for @question do |f| %>
<%= f.input :title, label: "Question Summary" %>
<%= f.input :details %>
<%= f.button :submit %>
<%end%>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<ul class="nav navbar-nav">
 <% if user_signed_in? %>
  <p><%= link_to "New Question", new_question_path, class: "navbar-right navbar-text navbar-link" %></p>
<% end%> 
</ul>

<% @questions.each do |question| %>
<div>
    <div class="question">
      <h2 class="q-title"><%= question.title %></h2>
      <% if user_signed_in? %>
        
          <%= link_to "View Question", question_path(question), class: "btn btn-default" %> 
    
      <%end %>
     
    </div>
</div>

<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<div class= "container">
    <h2><%= @question.title %></h2>
    <p>Posted By <%= @question.user.email %> <%= time_ago_in_words(@question.created_at) %> ago </p>
    <p><%= @question.details %></p>
    
    <h3>Answers:</h3>
    <%= render @question.answers %>
    
    <h3>Reply to Question:</h3>
    <%= render 'answers/form' %>
    
    <%= link_to "Back", questions_path %>
    <% if user_signed_in? %>
        <% if @question.user_id == current_user.id %>
            <%= link_to "Edit", edit_question_path(@question) %>
            <%= link_to "Delete", question_path(@question), method: :delete, data: { confirm: "Are you sure you want to Delete this Question?" } %>
        <% end %>
    <% end %>
</div>

app/views/static_pages/home.html.erb
<h1>How to Find Your Perfect Dog</h1>


<div class="box">
    <%= image_tag("collage.jpg", width: '250px')%>
    <h3><%= link_to "Survey!!!", new_survey_path %></h3>
</div>

<div class="box">
    <%= image_tag("bichon_frise.jpg", width: '250px')%>
    <h3><%= link_to "Toy Dogs", static_pages_toy_path %></h3>
</div>

<div class="box">
    <%= image_tag("Cavalier-King-Charles.jpg", width: '300px')%>
    <h3><%= link_to "Small Dogs", static_pages_small_path %></h3>
</div>

<div class="box">
    <%= image_tag("whippet.jpg", width: '300px')%>
    <h3><%= link_to "Medium Dogs", static_pages_medium_path %></h3>
</div>

<div class="box">
    <%= image_tag("Siberian-Husky-standing-outdoors-in-the-winter", width: '300px')%>
    <h3><%= link_to "Large Dogs", static_pages_large_path %></h3>
</div>

<div class="box">
    <%= image_tag("Bernese-Mountain-Dog-running.jpg", width: '300px')%>
    <h3><%= link_to "Extra Large Dogs", static_pages_xlarge_path %></h3>
</div>

app/views/static_pages/review.html.erb
<div class= "container">
    <h1>Reviews:</h1>
    
    
    <h2>Rabbitgoo No Pull Dog Harness</h2>
    <%= image_tag("review.jpg", width: '400px')%>
    <%= image_tag("size_chart.jpg", width: '400px')%>
    <p>Review by F. Kavanagh</p>
    <p>I bought this for our two strong lurchers to try help with their pulling. Due to an illness I find their sudden pulling painful if they see a cat/want to run over to another
    dog, so after seeing many possitive reviews I decided to try out their very inexpensive(€22 euro each) harness. Well to say they are a game changer is an understatement, the lead 
    clipping onto their chestmeans that its very difficult for them to pull and when they do they just end up turning themselves around. Its helped them to walk much better on the 
    leash and has helped save my arms and back a lot of pain. They barely pull anymore and we have so much more control. The Rabbitgoo harness have totally changed how our dogs walk.
    We are not worried about falling anymore because there is no more struggling to control the dogs. We saw a change immediately. I would recommend these harnesses to anyone
    wanting to end the constant pulling</p>

</div>

app/views/surveys/edit.html.erb
<div class= "container">
<h1>Editing Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>
</div>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Surveys</h1>

<table class="table">
  <thead>
    <tr>
      <th>Size</th>
      <th>Appartment</th>
      <th>Shed</th>
      <th>Energy</th>
      <th>Garden</th>
      <th>Children</th>
      <th>Works Long Hours</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.size %></td>
        <td><%= survey.appartment %></td>
        <td><%= survey.shed %></td>
        <td><%= survey.energy %></td>
        <td><%= survey.garden %></td>
        <td><%= survey.children %></td>
        <td><%= survey.wh %></td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<div class= "container">
<h1>New Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Back', surveys_path %>
</div>

app/views/surveys/show.html.erb
<div class= "container">
  <p id="notice"><%= notice %></p>
  
  <p>
    <strong>Size:</strong>
    <%= @survey.size %>
  </p>
  
  <p>
    <strong>Appartment:</strong>
    <%= @survey.appartment %>
  </p>
  
  <p>
    <strong>Shed:</strong>
    <%= @survey.shed %>
  </p>
  
  <p>
    <strong>Energy:</strong>
    <%= @survey.energy %>
  </p>
  
  <p>
    <strong>Garden:</strong>
    <%= @survey.garden %>
  </p>
  
  <p>
    <strong>Children:</strong>
    <%= @survey.children %>
  </p>
  
  <p>
    <strong>Work Long Hours:</strong>
    <%= @survey.wh %>
  </p>
  
  
  <p>Results:</p>
  <% if @survey.size == 'Toy' && @survey.shed == 'Low-Light'  && @survey.energy == 'Moderate' && @survey.children == 'no' && @survey.wh == 'yes'%>
  <li><%= link_to 'Shi Tzu', static_pages_toy_path, :class => "t2" %></li>
  <% elsif @survey.size == 'Toy' && @survey.shed == 'Low-Light'  && @survey.energy == 'Moderate' && @survey.children == 'yes' && @survey.wh == 'no'%>
  <li><%= link_to 'Bichan Friese', static_pages_toy_path %></li>
  <% elsif @survey.size == 'Toy' && @survey.shed == 'Low-Light'  && @survey.energy == 'Moderate' && @survey.children == 'no' && @survey.wh == 'no'%>
  <li><%= link_to 'Shi Tzu', static_pages_toy_path %></li>
  <li><%= link_to 'Bichan Friese', static_pages_toy_path%></li>
  <li><%= link_to 'Maltese', static_pages_toy_path %></li>
  <% elsif @survey.size == 'Toy' && @survey.shed == 'Low-Light'  && @survey.energy == 'High'%>
  <li><%= link_to 'Yorkshire Terrier', static_pages_toy_path %></li>
  <% elsif @survey.size == 'Toy' && @survey.shed == 'Moderate'  && @survey.energy == 'Moderate' && @survey.children == 'no' && @survey.wh == 'no'%>
  <li><%= link_to 'Pomeranian', static_pages_toy_path %></li>
  <% elsif @survey.size == 'Toy' && @survey.shed == 'Moderate'  && @survey.energy == 'High' && @survey.children == 'yes' && @survey.wh == 'no'%>
  <li><%= link_to 'Chihuahua', static_pages_toy_path %></li>
  <% elsif @survey.size == 'Small' && @survey.appartment == 'no' && @survey.shed == 'Low-Light'  && @survey.energy == 'High' && @survey.children == 'no' && @survey.wh == 'yes'%>
  <li><%= link_to 'West Highland Terrier', static_pages_small_path %></li> 
  <% elsif @survey.size == 'Small' && @survey.appartment == 'no' && @survey.shed == 'Moderate' && @survey.energy == 'High'%>
  <li><%= link_to 'Jack Russel Terrier', static_pages_small_path %></li>
  <% elsif @survey.size == 'Small' && @survey.appartment == 'no' && @survey.shed == 'High' && @survey.energy == 'High'%>
  <li><%= link_to 'Jack Russel Terrier', static_pages_small_path %></li>
  <% elsif @survey.size == 'Small' && @survey.appartment == 'yes' && @survey.shed == 'Moderate'  && @survey.energy == 'Moderate' && @survey.children == 'yes' && @survey.wh == 'yes'%>
  <li><%= link_to 'Cocker Spaniel', static_pages_small_path %></li>
  <% elsif @survey.size == 'Small' && @survey.appartment == 'yes' && @survey.shed == 'Moderate'  && @survey.energy == 'Moderate' && @survey.children == 'yes' && @survey.wh == 'no'%>
  <li><%= link_to 'Cavalier King Charles Spaniel', static_pages_small_path %></li>
  <li><%= link_to 'Beagle', static_pages_small_path %></li>
  <li><%= link_to 'Daschund', static_pages_small_path %></li>
  <% elsif @survey.size == 'Small' && @survey.appartment == 'yes' && @survey.shed == 'Heavy'  && @survey.energy == 'Moderate' && @survey.children == 'yes' && @survey.wh == 'no'%>
  <li><%= link_to 'Pug', static_pages_small_path %></li>
  <% elsif @survey.size == 'Small' && @survey.appartment == 'yes' && @survey.shed == 'Moderate'  && @survey.energy == 'High' && @survey.children == 'yes' && @survey.wh == 'no'%>
  <li><%= link_to 'Daschund', static_pages_small_path %></li>
  <% elsif @survey.size == 'Medium' && @survey.appartment == 'no' && @survey.shed == 'Moderate'  && @survey.energy == 'High' && quiz.garden == 'yes' && @survey.children == 'no' && @survey.wh == 'no'%>
  <li><%= link_to 'Border Collie', static_pages_medium_path %></li>
  <% elsif @survey.size == 'Medium' && @survey.appartment == 'no' && @survey.shed == 'Moderate'  && @survey.energy == 'Low' && @survey.garden == 'no' && @survey.children == 'yes' && @survey.wh == 'no'%>
  <li><%= link_to 'Bulldog', static_pages_mediums_path %></li>
  <% elsif @survey.size == 'Medium' && @survey.appartment == 'no' && @survey.shed == 'Moderate'  && @survey.energy == 'Moderate' && @survey.garden == 'yes' && @survey.children == 'no' && @survey.wh == 'no'%>
  <li><%= link_to 'Basset Hound', static_pages_medium_path %></li>
  <% elsif @survey.size == 'Medium' && @survey.appartment == 'no' && @survey.shed == 'Moderate'  && @survey.energy == 'Moderate' && @survey.garden == 'no' && @survey.children == 'no' && @survey.wh == 'no'%>
  <li><%= link_to 'Whippet', static_pages_medium_path %></li>
  <% elsif @survey.size == 'Medium' && @survey.appartment == 'no' && @survey.shed == 'Moderate'  && @survey.energy == 'Moderate' && @survey.garden == 'no' && @survey.children == 'no' && @survey.wh == 'yes'%>
  <li><%= link_to 'Staffy Bull Terrior', static_pages_medium_path %></li>
  <% elsif @survey.size == 'Medium' && @survey.appartment == 'no' && @survey.shed == 'Heavy'  && @survey.energy == 'Moderate' && @survey.garden == 'no' && @survey.children == 'no' && @survey.wh == 'no'%>
  <li><%=link_to 'Samoyed', static_pages_medium_path %></li>
  <% elsif @survey.size == 'Large' && @survey.appartment == 'yes' && @survey.shed == 'Low-Light'  && @survey.energy == 'Moderate' && @survey.garden == 'no' && @survey.children == 'no' && @survey.wh == 'yes'%>
  <li><%= link_to 'Poodle Standard', static_pages_large_path %></li>
  <% elsif @survey.size == 'Large' && @survey.appartment == 'yes' && @survey.shed == 'Moderate'  && @survey.energy == 'Moderate' && @survey.garden == 'no' && @survey.children == 'no' && @survey.wh == 'no'%>
  <li><%= link_to 'German Shephard', static_pages_large_path %>
  <li><%=link_to 'Greyhound', static_pages_large_path %></li>
  <% elsif @survey.size == 'Large' && @survey.appartment == 'yes' && @survey.shed == 'Moderate'  && @survey.energy == 'Low' && @survey.garden == 'no' && @survey.children == 'no' && @survey.wh == 'no'%>
  <li><%= link_to 'Greyhound', static_pages_large_path %></li>
  <% elsif @survey.size == 'Large' && @survey.appartment == 'yes' && @survey.shed == 'Moderate'  && @survey.energy == 'Moderate' && @survey.garden == 'yes' && @survey.children == 'yes' && @survey.wh == 'yes'%>
  <li><%= link_to 'Golden Retriever', static_pages_large_path %></li>
  <% elsif @survey.size == 'Large' && @survey.appartment == 'no' && @survey.shed == 'Moderate'  && @survey.energy == 'High' && @survey.garden == 'yes' && @survey.children == 'yes' && @survey.wh == 'no'%>
  <li><%=link_to 'Labrador', static_pages_large_path %></li>
  <li><%= link_to 'Boxer', static_pages_large_path %></li>
  <% elsif @survey.size == 'Large' && @survey.appartment == 'no' && @survey.shed == 'Moderate'  && @survey.energy == 'Moderate' && @survey.garden == 'yes' && @survey.children == 'no' && @survey.wh == 'no'%>
  <li><%= link_to 'Labrador', static_pages_large_path %></li>
  <li><%= link_to 'Boxer', static_pages_large_path %></li>
  <li><%= link_to 'Rotweiler', static_pages_large_path %></li>
  <% elsif @survey.size == 'Large' && @survey.appartment == 'no' && @survey.shed == 'Moderate'  && @survey.energy == 'High' && @survey.garden == 'yes' && @survey.children == 'no' && @survey.wh == 'no'%>
  <li><%= link_to 'Labrador', static_pages_large_path %></li>
  <li><%= link_to 'Boxer', static_pages_large_path %></li>
  <li><%= link_to 'Doberman', static_pages_large_path %></li>
  <% elsif @survey.size == 'Large' && @survey.appartment == 'no' && @survey.shed == 'Heavy'  && @survey.energy == 'Moderate' && @survey.garden == 'yes' && @survey.children == 'no' && @survey.wh == 'yes'%>
  <li><%= link_to 'Siberian Husky', static_pages_large_path %></li>
  <% elsif @survey.size == 'X-Large' && @survey.appartment == 'no' && @survey.shed == 'Moderate'  && @survey.energy == 'Low' && @survey.garden == 'yes' && @survey.children == 'no' && @survey.wh == 'yes'%>
  <li><%= link_to 'Irish Wolfhound', static_pages_xlarge_path %></li>
  <li><%= link_to 'Scottish Deerhound', static_pages_xlarge_path %></li>
  <li><%= link_to 'St Bernard', static_pages_xlarge_path %></li>
  <% elsif @survey.size == 'X-Large' && @survey.appartment == 'no' && @survey.shed == 'Moderate'  && @survey.energy == 'Low' && @survey.garden == 'yes' && @survey.children == 'no' && @survey.wh == 'no'%>
  <li><%= link_to 'Irish Wolfhound', static_pages_xlarge_path %></li>
  <li><%= link_to 'Scottish Deerhound', static_pages_xlarge_path %></li>
  <li><%= link_to 'St Bernard', static_pages_xlarge_path %></li>
  <li><%= link_to 'Mastiff', static_pages_xlarge_path %></li>
  <li><%= link_to 'Tibetan Mastiff', static_pages_xlarge_path %></li>
  <% elsif @survey.size == 'X-Large' && @survey.appartment == 'no' && @survey.shed == 'Moderate'  && @survey.energy == 'Moderate' && @survey.garden == 'yes' && @survey.children == 'no' && @survey.wh == 'no'%>
  <li><%= link_to 'Great Dane', static_pages_xlarge_path %></li>
  <li><%= link_to 'Scottish Deerhound', static_pages_xlarge_path %></li>
  <li><%= link_to 'St Bernard', static_pages_xlarge_path %></li>
  <% elsif @survey.size == 'X-Large' && @survey.appartment == 'no' && @survey.shed == 'Moderate'  && @survey.energy == 'Moderate' && @survey.garden == 'yes' && @survey.children == 'no' && @survey.wh == 'yes'%>
  <li><%= link_to 'Scottish Deerhound', static_pages_xlarge_path %></li>
  <li><%= link_to 'St Bernard', static_pages_xlarge_path %></li>
  <% elsif @survey.size == 'X-Large' && @survey.appartment == 'no' && @survey.shed == 'Moderate'  && @survey.energy == 'Moderate' && @survey.garden == 'no' && @survey.children == 'no'%>
  <li><%= link_to 'St Bernard', static_pages_xlarge_path %></li>
  <% elsif @survey.size == 'X-Large' && @survey.appartment == 'no' && @survey.shed == 'Heavy'  && @survey.energy == 'Moderate' && @survey.garden == 'yes' && @survey.children == 'no'%>
  <li><%= link_to 'Bernese Mountain Dog', static_pages_xlarge_path %></li>
  <% else %>
  <p>There is not currently a dog in the system that matches your needs</p>
  <% end %>
  <br>
  <%= link_to 'Edit', edit_survey_path(@survey) %> |
  <%= link_to 'Back', surveys_path %>
</div>