config/routes.rb
Rails.application.routes.draw do
  resources :surveys
  get 'static_pages/home'
  
  get 'static_pages/toy'
  
  get 'static_pages/small'
  
  get 'static_pages/medium'
  
  get 'static_pages/large'
   
  get 'static_pages/xlarge'
  
  get 'static_pages/review'
  
  get 'static_pages/health'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end
  resources :questions do
    resources :answers
  end
  root 'static_pages#home'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :user
    has_many :answers
end

app/models/survey.rb
class Survey < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  has_many :questions
  has_many :answers
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    before_action :find_question
    before_action :find_answer, only: [:edit, :update, :destroy]
    before_action :authenticate_user!
    
    def create
        @answer = @question.answers.create(answer_params)
        @answer.user_id = current_user.id
        
        if @answer.save
            redirect_to question_path(@question)
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @answer.update(answer_params)
            redirect_to question_path(@question)
        else
            render 'edit'
        end
    end
    
    def destroy
        @answer.destroy
        redirect_to question_path(@question)
    end

    private
    
    def answer_params
        params.require(:answer).permit(:content)
    end
    
    def find_question
        @question = Question.find(params[:question_id])
    end
    
    def find_answer
        @answer = @question.answers.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_post
    before_action :find_comment, only: [:edit, :update, :destroy] 
    before_action :authenticate_user!
    
    def create
        @comment = @post.comments.create(comment_params)
        @comment.user_id = current_user.id
        if @comment.save
            redirect_to post_path(@post)
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @comment.update(comment_params)
            redirect_to post_path(@post)
        else render 'edit'
        end
    end
    
    def destroy
        @comment.destroy
        redirect_to post_path(@post)
    end
    
    private
    
    def comment_params
        params.require(:comment).permit(:content)
    end
    
    def find_post
        @post = Post.find(params[:post_id])
    end
    
    def find_comment
         @comment = @post.comments.find(params[:id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    
    def index
        @posts = Post.all.order("created_at DESC")
    end
    
    def show
    end
    
    def new
        @post = current_user.posts.build
    end
    
    def create
        @post = current_user.posts.build(post_params)
        if @post.save
            redirect_to posts_path
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @post.update(post_params)
            redirect_to post_path
        else
            render 'edit'
        end
    end
    
    def destroy
        @post.destroy
        redirect_to posts_path
    end
    
    private
    
    def post_params
        params.require(:post).permit(:title, :description)
    end
    
    def find_post
         @post = Post.find(params[:id])
    end
    
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_action :find_question, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    
    def index
        @questions = Question.all.order("created_at DESC")
    end
    
    def show
    end
    
    def new
        @question = current_user.questions.build
    end
    
    def create
        @question = current_user.questions.build(question_params)
        if @question.save
            redirect_to questions_path
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @question.update(question_params)
            redirect_to question_path
        else
            render 'edit'
        end
    end
    
    def destroy
        @question.destroy
        redirect_to questions_path
    end
    
    private
    
    def question_params
        params.require(:question).permit(:title, :details)
    end
    
    def find_question
        @question = Question.find(params[:id])
    end
    
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def survey_params
      params.require(:survey).permit(:size, :appartment, :shed, :energy, :garden, :children, :wh)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <div class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Home", root_path, class: "navbar-brand" %>
         
        </div>
        <ul class="nav navbar-nav">
           <li><%= link_to "Survey", new_survey_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Blog", posts_path %></li>
            <li><%= link_to "Advise", questions_path %></li>
             <li><%= link_to "Dog Health", static_pages_health_path %></li>
            <li><%= link_to "Reviews", static_pages_review_path %></li>
          <% end %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li
          <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
        </ul>
       
        
          <div class="navbar-group pull-right right-nav">
            <button type="button" class="btn-mimi dropdown-toggle" data-toggle="dropdown">
              <span class="caret"></span>
              <span clas="sr-only">Dogs</span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Toy", static_pages_toy_path %></li>
              <li><%= link_to "Small", static_pages_small_path %></li>
              <li><%= link_to "Medium", static_pages_medium_path %></li>
              <li><%= link_to "Large", static_pages_large_path %></li>
              <li><%= link_to "XLarge", static_pages_xlarge_path %></li>
            </ul>
          </div>
      </div>
    </div>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
       
    <%= yield %>
  </body>
</html>